### ISSUE TITLE
Regression where dark mode uses the same background and foreground color (del)

### ISSUE THREAD

**Issue by csarven** [w3c/htmldiff-ui#12]
https://github.com/w3c/htmldiff-ui/commit/5f10049ff3d5fbb45e1bd64b7ee9868d678ff38b introduced an issue in which while in dark mode there are blocks with red color/background, and yellow seems to be missing in action, see, e.g.:

https://github.com/w3c/htmldiff-ui/commit/5f10049ff3d5fbb45e1bd64b7ee9868d678ff38b https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fnotifications%2F837221ddeeeb69ac123f1a766765ddf8f455f7e9%2Fprotocol.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fsolid%2Fnotifications%2F56ddf9f68c38c59a5ad4affe9a8fc919882882b5%2Fquick-protocol.html

Another example:

https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvc-data-model%2Ff6d5cec9d9d8073bf81864f6772aa734c98adf4d%2Findex.html&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fvc-data-model%2Fe57706068e3e61f5ab7a0fe57d80998a7e860a2a%2Findex.html

Possibly adjust `--diff-old-bg`, `--diff-new-bg`.

**Comment by tabatkins** [comment]
PR submitted to fix this (and all remaining colors I could find) https://github.com/whatwg/whatwg.org/pull/434

**Comment by dontcallmedom** [comment]
@tabatkins is this something you can help with?

**Comment by tabatkins** [comment]
I mean, this is precisely the issue I raised as a possibility - a document that doesn't understand darkmode at all, rendered on a system that requests dark mode, will get the darkmode diff backgrounds but use its lightmode text colors, giving us the opposite readability problem of before.  The answer is to make your documents darkmode-aware, which is respectful of users in the first place.

**Comment by csarven** [comment]
Do you mean for example that https://www.w3.org/StyleSheets/TR/2021/base.css needs to be brought up to speed for dark mode or that where base is used, https://www.w3.org/StyleSheets/TR/2021/dark.css ( https://www.w3.org/StyleSheets/TR/2021/#dark ) should also be included in the same document?

AFAICT, the example documents in the initial comment are not touching the dark/lightmode colors.

**Comment by tabatkins** [comment]
>  where base is used, https://www.w3.org/StyleSheets/TR/2021/dark.css ( https://www.w3.org/StyleSheets/TR/2021/#dark ) should also be included in the same document?

This, yes.

(Bikeshed *should* be including that by default, but I wasn't informed it was ready at the time. I'll be fixing that shortly.)

> AFAICT, the example documents in the initial comment are not touching the dark/lightmode colors.

Right, that means the document isn't darkmode-aware.

**Comment by elf-pavlik** [comment]
Maybe adding a simple button to toggle the highlight colors theme would provide a way to manually change them without opening the dev tools?

>  The answer is to make your documents darkmode-aware, which is respectful of users in the first place.

The suggested button could have a tooltip kindly recommending it.

**Comment by iherman** [comment]
I hope the respec developers are aware of the necessary changes as well... at the moment, respec does not add that dark mode style sheet, which creates difficulties with diff.

**Comment by adampage** [comment]
I came looking to log this issue and found that y’all beat me to it. I have nothing more to add, but I did capture this quick video cap along the way which I may as well add for a visual aid. 😅

<img alt="A video capture demonstrating how the colors for ins and del elements in htmldiff’d W3C documents become unreadable in dark mode" src="https://github.com/w3c/htmldiff-ui/assets/1395630/332c9805-35e1-442a-90b2-d41216a5391f" width="620" />

**Comment by lianqi** [comment]
The [diff doc of Code of Conduct](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2Fpolicies%2Fcode-of-conduct%2F&doc2=https%3A%2F%2Fwww.w3.org%2Fpolicies%2Fcode-of-conduct%2Fdrafts%2F20240202%2F) in dark mode dragged me here.  Happy to see it's been issued and thanks @adampage for the visual aid.

**Comment by tabatkins** [comment]
PR submitted to fix this, now that Bikeshed emits useful signals to key off of.

(I also finally fixed the problem where publishing for /TR wouldn't include the W3C darkmode styles, because nobody had told me they were ready. So new docs published to /TR will get darkmode, yay!)
