### ISSUE TITLE
Why are the modules in the cgi subroutine commented out?

### ISSUE THREAD

**Issue by hbcondo** [w3c/htmldiff-ui#2]
These are showing as commented out but aren't they required to perform the http requests?

https://github.com/w3c/htmldiff-ui/blob/8237878a724ecd6f6f419cb5b6b81a19284b351d/htmldiff.pl#L496-L497

**Comment by bert-github** [comment]
The cgi subroutine is currently not used at all, only the cli subroutine is. The Python script htmldiff handles the CGI interaction and then calls htmldiff.pl as a command line utility.
