### ISSUE TITLE
DOCTYPE stripped

### ISSUE THREAD

**Issue by annevk** [w3c/htmldiff-ui#4]
As can be seen from the various diff links on https://github.com/whatwg/html/pull/5629 the output does not contain `<!DOCTYPE html>` despite the input doing so. It would be nice if the output was closer to being standards compliant.

**Comment by gosko** [comment]
This seems to be due to the serialization done by html5lib in [tidyFile()](https://github.com/w3c/htmldiff-ui/blob/master/htmldiff#L89)

**Comment by annevk** [comment]
I hear prepending the output with `<!doctype html>` might be our best bet (from a html5lib maintainer). I checked and this isn't just a problem for WHATWG, it also affects things like https://pr-preview.s3.amazonaws.com/w3c/webappsec-csp/435/febc4eb...antosart:5769bd0.html.

**Comment by annevk** [comment]
Thanks @dontcallmedom!
